module.exports = {
  SUCCESS_CODE: 200,
  CREATED: 201,
  REQ_DATING_ERROR_CODE: 204,
  ERROR_CODE: 400,
  INVALID_CODE: 401,
  FORBIDDEN_CODE: 403,
  INACTIVATE: 406,
  NOT_FOUND: 404,
  CONFLICT: 409,
  SERVER_ERROR: 500,
  REQUEST_NOT_FOUND: "Request not found",
  EMAIL_ALREADY_REGISTERED: "Email already registered.",
  INVAILID_DATA: "Registration form data is not correct.",
  USER_SAVE_SUCCESS: "Registration completed successfully",
  USER_NOT_AUTHORIZED: "You are not Authorized",
  SOMETHING_WENT_WRONG: "Something went wrong",
  USER_LOGIN_SUCCESS: "User Login successfully",
  USER_EMAIL_PASSWORD: "You have entered an invalid email or password",
  INVALID_TOKEN: "Invalid Token",
  USER_EMAIL_NOT_REGISTERED: "This email is not registered.",
  NO_DATA_FOUND: "No data found",
  PROJECT_SAVE_SUCCESS:"Project saved successfully",
  PROJECT_UPDATE_SUCCESS:"Project updated successfully",
  PROJECT_RETRIEVE_SUCCESS:"Project retrived successfully",
  USER_DATA_UPDATE_SUCCESS: "User update successfully",
};
